In [1]:
import geopandas as gpd
import pandas as pd
from shapely import wkb

import os
import sys

# use absolute path here
project_path = "/mnt/School/PhD/AI221/Project/"
sys.path.insert(0, project_path)

from src.data_extraction.utils.constants import data_path

## 1. Reading datasets

In [2]:
ph_bounds = gpd.read_file(os.path.join(data_path,"ph_adm3_municities/PH_Adm3_MuniCities.shp.shp"))
ph_bounds = ph_bounds[ph_bounds["geo_level"] == "City"]
ph_bounds.head()

,adm1_psgc,adm2_psgc,adm3_psgc,adm3_en,geo_level,len_crs,area_crs,len_km,area_km2,geometry
4,100000000,102800000,102805000,City of Batac,City,66661,158252391,66,158.0,"POLYGON ((247341.309 2003933.537, 247293.327 2..."
11,100000000,102800000,102812000,City of Laoag,City,53964,110146974,53,110.0,"POLYGON ((248393.247 2016552.78, 248424.831 20..."
28,100000000,102900000,102906000,City of Candon,City,62247,77652664,62,77.0,"POLYGON ((230319.064 1907309.065, 230338.289 1..."
56,100000000,102900000,102934000,City of Vigan,City,25067,24485368,25,24.0,"POLYGON ((221597.447 1945779.016, 221718.087 1..."
70,100000000,103300000,103314000,City of San Fernando,City,54233,99006121,54,99.0,"POLYGON ((225191.401 1841887.86, 225339.01 184..."

In [3]:
# Getting unique PSGCs
ph_bounds.adm3_psgc.nunique()

149

In [4]:
groundsource_df = pd.read_parquet("../../data/groundsource.parquet")
groundsource_df["start_date"] = pd.to_datetime(groundsource_df["start_date"])
groundsource_df["end_date"] = pd.to_datetime(groundsource_df["end_date"])
groundsource_df.head()

,uuid,area_km2,geometry,start_date,end_date
0,5acc1866dd6644dfa572f02ae3d54aa4,91.678015,"b""\x01\x06\x00\x00\x00\x02\x00\x00\x00\x01\x03...",2000-01-01,2000-01-01
1,f80fccbefb1346a9b568907086e65226,609.968365,b'\x01\x06\x00\x00\x00\x02\x00\x00\x00\x01\x03...,2000-01-01,2000-01-01
2,d5c49c9e2c2045bfbfd6e3b3865efc3f,0.099688,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,2000-01-24,2000-01-24
3,ce7f01a29de040b39e138f198fc39d86,0.548906,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,2000-01-30,2000-01-30
4,eb047dfea9ed406485010853226e0170,0.236562,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,2000-01-30,2000-01-30

In [5]:
# Filter only between 2022-2025
study_start = pd.Timestamp("2022-01-01")
study_end = pd.Timestamp("2025-12-31")

qualifying_mask = (
    (groundsource_df["end_date"] >= study_start) &
    (groundsource_df["start_date"] <= study_end)
)

groundsource_df = groundsource_df[qualifying_mask]

# Clip dates to fit within the study period
groundsource_df["start_date"] = groundsource_df["start_date"].clip(lower=study_start, upper=study_end)
groundsource_df["end_date"] = groundsource_df["end_date"].clip(lower=study_start, upper=study_end)
groundsource_df = groundsource_df[groundsource_df["start_date"] <= groundsource_df["end_date"]].copy()
groundsource_df.head()

,uuid,area_km2,geometry,start_date,end_date
1380478,1546b667b4584944bb0f1d4282ae5395,4.556350,"b""\x01\x06\x00\x00\x00\x02\x00\x00\x00\x01\x03...",2022-01-01,2022-01-01
1380670,8a4fcb98f4974577a58003f9b888c15b,0.023638,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,2022-01-01,2022-01-01
1380721,f05f2beb93f6469980fb856dc3849068,304.795109,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x1c\x00...,2022-01-01,2022-01-01
1380797,d8eb1f862d4c4c5ebf46e62d343922ec,11.823934,"b""\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...",2022-01-01,2022-01-01
1380971,70b2072802c1413a977188f1ad08afb5,625.314062,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x0f\x00...,2022-01-01,2022-01-03

In [6]:
# Validation: non-clipped months exist
groundsource_df[groundsource_df["start_date"] < groundsource_df["end_date"]].head()

,uuid,area_km2,geometry,start_date,end_date
1380971,70b2072802c1413a977188f1ad08afb5,625.314062,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x0f\x00...,2022-01-01,2022-01-03
1381057,3840715a51e4445dae4852e7966b440f,605.714725,"b""\x01\x03\x00\x00\x00\x01\x00\x00\x00\n\x00\x...",2022-01-01,2022-01-03
1381141,c0eef5633052468b90576a98f3104ffe,1354.479456,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x16\x00...,2022-01-01,2022-01-02
1381149,c1e7ed0e19b64f72acd4b7212c4e09aa,0.038935,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,2022-01-01,2022-01-02
1381151,c20aa6c35190456eabb3144538f2e02c,0.236287,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,2022-01-01,2022-01-02

## 2. Getting PH-only flooding events

In [7]:
# Use wkb.loads to turn bytes into a Shapely object
groundsource_df['geometry'] = groundsource_df['geometry'].apply(lambda x: wkb.loads(x))

# Create a GeoDataFrame with CRS being EPSG:4326 (WGS 84) as per the Groundsource docs
gs_gdf = gpd.GeoDataFrame(groundsource_df, geometry='geometry', crs="EPSG:4326")

In [8]:
# Standardize both datasets to a common CRS
gs_gdf = gs_gdf.to_crs(epsg=4326)
ph_admin = ph_bounds.to_crs(epsg=4326)

# Use the Representative Point for the Groundsource data, which
# turns complex shapes into a single 'seed' point inside the area
gs_gdf['join_geometry'] = gs_gdf.geometry.representative_point()

# Use a Spatial Join (sjoin) with predicate intersects, basically 
# getting all cities where the representative point intersects with.
tagged_df = gpd.sjoin(
    gs_gdf,
    ph_admin[["adm3_psgc", 'geo_level', 'geometry']],
    how="left", 
    predicate="intersects" 
)

In [10]:
# Getting only records inside the PH Cities/Municipalities
cleaned_gdf = tagged_df[~tagged_df.adm3_psgc.isna()]
cleaned_gdf.head()

,uuid,area_km2,geometry,start_date,end_date,join_geometry,index_right,adm3_psgc,geo_level
1383223,eab0bfe86aeb45cdbd1859e2aae325f9,212.500434,"POLYGON ((122.94193 10.85978, 122.98532 10.832...",2022-01-01,2022-01-02,POINT (123.09825 10.76178),725.0,604528000.0,City
1383223,eab0bfe86aeb45cdbd1859e2aae325f9,212.500434,"POLYGON ((122.94193 10.85978, 122.98532 10.832...",2022-01-01,2022-01-02,POINT (123.09825 10.76178),723.0,604526000.0,City
1383223,eab0bfe86aeb45cdbd1859e2aae325f9,212.500434,"POLYGON ((122.94193 10.85978, 122.98532 10.832...",2022-01-01,2022-01-02,POINT (123.09825 10.76178),728.0,604531000.0,City
1383223,eab0bfe86aeb45cdbd1859e2aae325f9,212.500434,"POLYGON ((122.94193 10.85978, 122.98532 10.832...",2022-01-01,2022-01-02,POINT (123.09825 10.76178),720.0,604523000.0,City
1383223,eab0bfe86aeb45cdbd1859e2aae325f9,212.500434,"POLYGON ((122.94193 10.85978, 122.98532 10.832...",2022-01-01,2022-01-02,POINT (123.09825 10.76178),701.0,604504000.0,City

In [12]:
# Deduplication and removing unnecessary columns
urban_flood_df = cleaned_gdf[[
    "adm3_psgc",
    "geo_level",
    "start_date",
    "end_date"
]].drop_duplicates().reset_index(drop=True)
urban_flood_df["adm3_psgc"] = urban_flood_df["adm3_psgc"].astype(int)

urban_flood_df

       adm3_psgc geo_level start_date   end_date
0      604528000      City 2022-01-01 2022-01-02
1      604526000      City 2022-01-01 2022-01-02
2      604531000      City 2022-01-01 2022-01-02
3      604523000      City 2022-01-01 2022-01-02
4      604504000      City 2022-01-01 2022-01-02
...          ...       ...        ...        ...
9651   702223000      City 2025-12-23 2025-12-24
9652   330100000      City 2025-12-24 2025-12-24
9653  1004215000      City 2025-12-25 2025-12-25
9654  1004210000      City 2025-12-25 2025-12-25
9655  1004209000      City 2025-12-25 2025-12-25

[9656 rows x 4 columns]

In [13]:
# Checking the counts of cities
urban_flood_df.nunique()

adm3_psgc     149
geo_level       1
start_date    832
end_date      841
dtype: int64

In [14]:
groundsource_filename = os.path.join(data_path,"urban_flood_groundsource_df.csv")
urban_flood_df.to_csv(groundsource_filename, index=False)