In [1]:
import os
import geopandas as gpd
import numpy as np
import pandas as pd

import sys

# use absolute path here
project_path = "/mnt/School/PhD/AI221/Project/"
sys.path.insert(0, project_path)

from src.data_extraction.utils.constants import data_path

In [2]:
urban_datasets_dict = {
    "active_flood_days": "urban_active_flood_days.csv",
    "annual_nightlights": "urban_annual_nightlights.csv",
    "flood_control_projects": "urban_flood_control_projects.csv",
    "monthly_rainfall": "urban_monthly_rainfall.csv",
    "osm_metrics": "urban_osm_metrics.csv",
    "twi_metrics": "urban_twi_metrics.csv",
}

### Setting keys

In [18]:
psgc_join_key = "adm3_psgc"
year_month_join_key = [psgc_join_key, "year_month"]
year_join_key = [psgc_join_key, "year"]
unique_keys = year_join_key + ["year_month"]

### Loading datasets

In [4]:
ph_bounds = gpd.read_file(os.path.join(data_path,"ph_adm3_municities/PH_Adm3_MuniCities.shp.shp"))
ph_bounds = ph_bounds[ph_bounds["geo_level"] == "City"]
ph_bounds.head()

,adm1_psgc,adm2_psgc,adm3_psgc,adm3_en,geo_level,len_crs,area_crs,len_km,area_km2,geometry
4,100000000,102800000,102805000,City of Batac,City,66661,158252391,66,158.0,"POLYGON ((247341.309 2003933.537, 247293.327 2..."
11,100000000,102800000,102812000,City of Laoag,City,53964,110146974,53,110.0,"POLYGON ((248393.247 2016552.78, 248424.831 20..."
28,100000000,102900000,102906000,City of Candon,City,62247,77652664,62,77.0,"POLYGON ((230319.064 1907309.065, 230338.289 1..."
56,100000000,102900000,102934000,City of Vigan,City,25067,24485368,25,24.0,"POLYGON ((221597.447 1945779.016, 221718.087 1..."
70,100000000,103300000,103314000,City of San Fernando,City,54233,99006121,54,99.0,"POLYGON ((225191.401 1841887.86, 225339.01 184..."

In [5]:
# Loading feature dataframes
active_flood_days_df = pd.read_csv(os.path.join(data_path, "urban_active_flood_days.csv"))
active_flood_days_df = active_flood_days_df.rename(
    columns={
        "psgc": "adm3_psgc",
        "month_year": "year_month"
    }
)

active_flood_days_df

       adm3_psgc year_month  reported_active_flood_days
0      102805000    2022-01                           2
1      102805000    2022-08                           3
2      102805000    2022-10                           5
3      102805000    2023-06                           2
4      102805000    2023-07                           5
...          ...        ...                         ...
2945  1908703000    2025-05                           6
2946  1908703000    2025-06                           1
2947  1908703000    2025-07                           3
2948  1908703000    2025-08                           4
2949  1908703000    2025-09                           1

[2950 rows x 3 columns]

In [6]:
flood_control_projects_df = pd.read_csv(os.path.join(data_path, "urban_flood_control_projects.csv"))
flood_control_projects_df = flood_control_projects_df.rename(
    columns={
        colname: f"fcp_{colname}"
        for colname in flood_control_projects_df.columns
        if colname not in year_month_join_key
    }
)
flood_control_projects_df.head()

,adm3_psgc,year_month,fcp_action_construction,fcp_action_rehabilitation,fcp_action_repair,fcp_action_improvement,fcp_action_extension,fcp_asset_drainage_system,fcp_asset_slope_protection,fcp_asset_bank_protection,...,fcp_budget__Small (5M-20M)_roll_9M,fcp_budget__Small (5M-20M)_roll_1Y,fcp_budget__Medium (20M-100M)_roll_3M,fcp_budget__Medium (20M-100M)_roll_6M,fcp_budget__Medium (20M-100M)_roll_9M,fcp_budget__Medium (20M-100M)_roll_1Y,fcp_budget__Large (>100M)_roll_3M,fcp_budget__Large (>100M)_roll_6M,fcp_budget__Large (>100M)_roll_9M,fcp_budget__Large (>100M)_roll_1Y
0,102805000,2022-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,102805000,2022-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,102805000,2022-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,102805000,2022-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,102805000,2022-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
osm_metrics_df = pd.read_csv(os.path.join(data_path, "urban_osm_metrics.csv"))
osm_metrics_df = osm_metrics_df.drop(columns=["city_name"])
osm_metrics_df = osm_metrics_df .rename(
    columns={
        "psgc": "adm3_psgc"
    }
)
osm_metrics_df = osm_metrics_df.rename(
    columns={
        colname: f"osm_{colname}"
        for colname in osm_metrics_df.columns
        if colname not in year_month_join_key + ["year"]
    }
)

osm_metrics_df.head()

,adm3_psgc,year,osm_poi_count,osm_large_water_m,osm_small_water_m,osm_building_area_m2,osm_gray_zones_area_m2,osm_green_zones_area_m2,osm_poi_per_km2,osm_large_water_m_per_km2,osm_small_water_m_per_km2,osm_building_coverage_ratio,osm_gray_zones_coverage_ratio,osm_green_zones_coverage_ratio
0,401005000,2022,86.0,63093.631236,124197.998664,8.293202e+06,1.496309e+07,1.100982e+07,0.313370,229.902631,452.556718,0.030219,0.054523,0.040118
1,401005000,2023,85.0,63973.789556,124198.963310,8.309308e+06,1.544018e+07,1.106789e+07,0.309726,233.109781,452.560233,0.030278,0.056261,0.040330
2,401005000,2024,78.0,64606.507373,129561.679285,8.351656e+06,1.728678e+07,1.106522e+07,0.284219,235.415299,472.101073,0.030432,0.062990,0.040320
3,401005000,2025,79.0,68793.927401,130540.962357,2.534504e+07,1.883119e+07,2.562899e+07,0.287863,250.673556,475.669416,0.092353,0.068618,0.093388
4,105503000,2022,18.0,78755.534822,128941.933865,4.540227e+05,9.022245e+06,1.165701e+07,0.111063,485.935375,795.594203,0.002801,0.055669,0.071926

In [8]:
annual_nightlights_df = pd.read_csv(os.path.join(data_path, "urban_annual_nightlights.csv"))
annual_nightlights_df = annual_nightlights_df .rename(
    columns={
        "psgc": "adm3_psgc"
    }
)
annual_nightlights_df = annual_nightlights_df .rename(
    columns={
        colname: "nightlight_" + colname.replace("_nightlight", "")
        for colname in annual_nightlights_df.columns
        if colname not in year_month_join_key + ["year"]
    }
)
annual_nightlights_df

,adm3_psgc,year,nightlight_annual_mean,nightlight_annual_max,nightlight_annual_std,nightlight_mean_pc1,nightlight_max_pc1,nightlight_std_pc1,nightlight_mean_pc2,nightlight_max_pc2,nightlight_std_pc2
0,102805000,2022,0.494240,19.0,1.352149,-7.669355,0.0,27.581887,3.095622,131.0,9.194335
1,102805000,2023,0.595622,19.0,1.427617,-7.669355,0.0,27.581887,3.095622,131.0,9.194335
2,102805000,2024,0.637097,22.0,1.485213,-7.669355,0.0,27.581887,3.095622,131.0,9.194335
3,102812000,2022,1.673171,19.0,2.186175,-57.401626,0.0,100.789387,0.656911,62.0,15.765487
4,102812000,2023,1.962602,18.0,2.238662,-57.401626,0.0,100.789387,0.656911,62.0,15.765487
...,...,...,...,...,...,...,...,...,...,...,...
442,1903617000,2023,2.368421,11.0,2.251355,-34.399381,0.0,41.700149,5.176471,27.0,6.809423
443,1903617000,2024,2.715170,11.0,2.560594,-34.399381,0.0,41.700149,5.176471,27.0,6.809423
444,1908703000,2022,1.437882,14.0,2.976779,-35.890244,0.0,83.879003,7.075203,72.0,14.474271
445,1908703000,2023,1.847251,20.0,3.740444,-35.890244,0.0,83.879003,7.075203,72.0,14.474271
446,1908703000,2024,2.073320,25.0,4.400833,-35.890244,0.0,83.879003,7.075203,72.0,14.474271

In [9]:
twi_metrics_df = pd.read_csv(os.path.join(data_path, "urban_twi_metrics.csv"))
twi_metrics_df  = twi_metrics_df.drop(columns=["adm3_en"])
twi_metrics_df

      adm3_psgc  mean_twi    max_twi   std_twi
0     102805000 -3.754234  20.971954  4.242962
1     102812000 -2.450579  20.181175  4.329910
2     102906000 -3.141669  20.913902  3.924423
3     102934000 -2.407162  30.716255  3.613563
4     103314000 -4.519191  33.818222  3.077760
..          ...       ...        ...       ...
144  1705205000 -1.366543  32.493546  4.429605
145  1731500000 -4.831936  34.306232  2.769698
146  1900702000 -4.203873  34.066833  3.008664
147  1903617000 -4.372182  17.165810  2.615103
148  1908703000 -1.437355  31.992622  4.698647

[149 rows x 4 columns]

In [10]:
monthly_rainfall_df = pd.read_csv(os.path.join(data_path, "urban_monthly_rainfall.csv"))
monthly_rainfall_df

       adm3_psgc     date         avg
0      102805000  2022-01   27.651221
1      102812000  2022-01   26.956228
2      102906000  2022-01   26.493692
3      102934000  2022-01   25.126945
4      103314000  2022-01   16.391532
...          ...      ...         ...
7147  1705205000  2024-11  121.675376
7148  1731500000  2024-11   77.391540
7149  1900702000  2024-11  162.410731
7150  1903617000  2024-11  198.439368
7151  1908703000  2024-11  186.061323

[7152 rows x 3 columns]

## Consolidating data

In [11]:
# Constant; one value for all year-months
consolidated_df_twi = pd.merge(
    ph_bounds[["adm3_psgc", "adm3_en"]],
    twi_metrics_df,
    on=psgc_join_key,
    how="left"
)
consolidated_df_twi.shape

(149, 5)

In [12]:
# Builds the year-month permutations
consolidated_df_rain = pd.merge(
    consolidated_df_twi,
    monthly_rainfall_df,
    on=psgc_join_key,
    how="left"
)
consolidated_df_rain = consolidated_df_rain.rename(
    columns={
        "date": "year_month",
        "avg": "monthly_avg_rainfall",
    }
)
consolidated_df_rain["year"] = consolidated_df_rain["year_month"].apply(
    lambda x: int(x.split("-")[0])
)
consolidated_df_rain.shape

(7152, 8)

In [14]:
# Annual data
consolidated_df_osm = pd.merge(
    consolidated_df_rain,
    osm_metrics_df,
    on=year_join_key,
    how="outer"
)
consolidated_df_osm.shape

(7152, 20)

In [15]:
# Monthly data
consolidated_df_fcp = pd.merge(
    consolidated_df_osm,
    flood_control_projects_df,
    on=year_month_join_key,
    how="outer"
)
consolidated_df_fcp.shape

(7152, 150)

In [17]:
# Annual data
consolidated_dataframe_nightlights = pd.merge(
    consolidated_df_fcp,
    annual_nightlights_df,
    on=year_join_key,
    how="outer"
)
consolidated_dataframe_nightlights.shape

(7152, 159)

In [24]:
# Monthly data
final_consolidated_dataframe_nightlights = pd.merge(
    consolidated_dataframe_nightlights,
    active_flood_days_df,
    on=year_month_join_key,
    how="outer"
).drop_duplicates(subset=unique_keys)
final_consolidated_dataframe_nightlights

,adm3_psgc,adm3_en,mean_twi,max_twi,std_twi,year_month,monthly_avg_rainfall,year,osm_poi_count,osm_large_water_m,...,nightlight_annual_mean,nightlight_annual_max,nightlight_annual_std,nightlight_mean_pc1,nightlight_max_pc1,nightlight_std_pc1,nightlight_mean_pc2,nightlight_max_pc2,nightlight_std_pc2,reported_active_flood_days
0,102805000,City of Batac,-3.754234,20.971954,4.242962,2022-01,27.651221,2022,11.0,34518.304560,...,0.49424,19.0,1.352149,-7.669355,0.0,27.581887,3.095622,131.0,9.194335,2.0
1,102805000,City of Batac,-3.754234,20.971954,4.242962,2022-02,5.619919,2022,11.0,34518.304560,...,0.49424,19.0,1.352149,-7.669355,0.0,27.581887,3.095622,131.0,9.194335,NaN
2,102805000,City of Batac,-3.754234,20.971954,4.242962,2022-03,1.946543,2022,11.0,34518.304560,...,0.49424,19.0,1.352149,-7.669355,0.0,27.581887,3.095622,131.0,9.194335,NaN
3,102805000,City of Batac,-3.754234,20.971954,4.242962,2022-04,56.003378,2022,11.0,34518.304560,...,0.49424,19.0,1.352149,-7.669355,0.0,27.581887,3.095622,131.0,9.194335,NaN
4,102805000,City of Batac,-3.754234,20.971954,4.242962,2022-05,268.542795,2022,11.0,34518.304560,...,0.49424,19.0,1.352149,-7.669355,0.0,27.581887,3.095622,131.0,9.194335,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7147,1908703000,City of Cotabato,-1.437355,31.992622,4.698647,2025-08,307.954037,2025,37.0,175601.776761,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
7148,1908703000,City of Cotabato,-1.437355,31.992622,4.698647,2025-09,348.655717,2025,37.0,175601.776761,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
7149,1908703000,City of Cotabato,-1.437355,31.992622,4.698647,2025-10,339.680996,2025,37.0,175601.776761,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7150,1908703000,City of Cotabato,-1.437355,31.992622,4.698647,2025-11,236.224148,2025,37.0,175601.776761,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7151,1908703000,City of Cotabato,-1.437355,31.992622,4.698647,2025-12,95.378809,2025,37.0,175601.776761,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
for col in final_consolidated_dataframe_nightlights:
    print(col)

adm3_psgc
adm3_en
mean_twi
max_twi
std_twi
year_month
monthly_avg_rainfall
year
osm_poi_count
osm_large_water_m
osm_small_water_m
osm_building_area_m2
osm_gray_zones_area_m2
osm_green_zones_area_m2
osm_poi_per_km2
osm_large_water_m_per_km2
osm_small_water_m_per_km2
osm_building_coverage_ratio
osm_gray_zones_coverage_ratio
osm_green_zones_coverage_ratio
fcp_action_construction
fcp_action_rehabilitation
fcp_action_repair
fcp_action_improvement
fcp_action_extension
fcp_asset_drainage_system
fcp_asset_slope_protection
fcp_asset_bank_protection
fcp_asset_linear_canal
fcp_asset_dike_levee
fcp_asset_coastal_defense
fcp_asset_active_control
fcp_protects_roadway
fcp_protects_education
fcp_protects_residential
fcp_protects_agricultural
fcp_waterbody_river
fcp_waterbody_creek
fcp_waterbody_coastal
fcp_waterbody_urban_runoff
fcp_is_multi_phase
fcp_total_projects
fcp_budget__Micro (<5M)
fcp_budget__Small (5M-20M)
fcp_budget__Medium (20M-100M)
fcp_budget__Large (>100M)
fcp_action_construction_roll_3M
fcp_action_construction_roll_6M
fcp_action_construction_roll_9M
fcp_action_construction_roll_1Y
fcp_action_rehabilitation_roll_3M
fcp_action_rehabilitation_roll_6M
fcp_action_rehabilitation_roll_9M
fcp_action_rehabilitation_roll_1Y
fcp_action_repair_roll_3M
fcp_action_repair_roll_6M
fcp_action_repair_roll_9M
fcp_action_repair_roll_1Y
fcp_action_improvement_roll_3M
fcp_action_improvement_roll_6M
fcp_action_improvement_roll_9M
fcp_action_improvement_roll_1Y
fcp_action_extension_roll_3M
fcp_action_extension_roll_6M
fcp_action_extension_roll_9M
fcp_action_extension_roll_1Y
fcp_asset_drainage_system_roll_3M
fcp_asset_drainage_system_roll_6M
fcp_asset_drainage_system_roll_9M
fcp_asset_drainage_system_roll_1Y
fcp_asset_slope_protection_roll_3M
fcp_asset_slope_protection_roll_6M
fcp_asset_slope_protection_roll_9M
fcp_asset_slope_protection_roll_1Y
fcp_asset_bank_protection_roll_3M
fcp_asset_bank_protection_roll_6M
fcp_asset_bank_protection_roll_9M
fcp_asset_bank_protection_roll_1Y
fcp_asset_linear_canal_roll_3M
fcp_asset_linear_canal_roll_6M
fcp_asset_linear_canal_roll_9M
fcp_asset_linear_canal_roll_1Y
fcp_asset_dike_levee_roll_3M
fcp_asset_dike_levee_roll_6M
fcp_asset_dike_levee_roll_9M
fcp_asset_dike_levee_roll_1Y
fcp_asset_coastal_defense_roll_3M
fcp_asset_coastal_defense_roll_6M
fcp_asset_coastal_defense_roll_9M
fcp_asset_coastal_defense_roll_1Y
fcp_asset_active_control_roll_3M
fcp_asset_active_control_roll_6M
fcp_asset_active_control_roll_9M
fcp_asset_active_control_roll_1Y
fcp_protects_roadway_roll_3M
fcp_protects_roadway_roll_6M
fcp_protects_roadway_roll_9M
fcp_protects_roadway_roll_1Y
fcp_protects_education_roll_3M
fcp_protects_education_roll_6M
fcp_protects_education_roll_9M
fcp_protects_education_roll_1Y
fcp_protects_residential_roll_3M
fcp_protects_residential_roll_6M
fcp_protects_residential_roll_9M
fcp_protects_residential_roll_1Y
fcp_protects_agricultural_roll_3M
fcp_protects_agricultural_roll_6M
fcp_protects_agricultural_roll_9M
fcp_protects_agricultural_roll_1Y
fcp_waterbody_river_roll_3M
fcp_waterbody_river_roll_6M
fcp_waterbody_river_roll_9M
fcp_waterbody_river_roll_1Y
fcp_waterbody_creek_roll_3M
fcp_waterbody_creek_roll_6M
fcp_waterbody_creek_roll_9M
fcp_waterbody_creek_roll_1Y
fcp_waterbody_coastal_roll_3M
fcp_waterbody_coastal_roll_6M
fcp_waterbody_coastal_roll_9M
fcp_waterbody_coastal_roll_1Y
fcp_waterbody_urban_runoff_roll_3M
fcp_waterbody_urban_runoff_roll_6M
fcp_waterbody_urban_runoff_roll_9M
fcp_waterbody_urban_runoff_roll_1Y
fcp_is_multi_phase_roll_3M
fcp_is_multi_phase_roll_6M
fcp_is_multi_phase_roll_9M
fcp_is_multi_phase_roll_1Y
fcp_total_projects_roll_3M
fcp_total_projects_roll_6M
fcp_total_projects_roll_9M
fcp_total_projects_roll_1Y
fcp_budget__Micro (<5M)_roll_3M
fcp_budget__Micro (<5M)_roll_6M
fcp_budget__Micro (<5M)_roll_9M
fcp_budget__Micro (<5M)_roll_1Y
fcp_budget__Small (5M-20M)_roll_3M
fcp_budget__Small (5M-20M)_roll_6M
fcp_budget__Small (5M-20M)_roll_9M
fcp_budget__Small (5M-20M)_roll_1Y
fcp_budget__Medium (20M-100M)_roll_3M
fcp_budget__Medium (20M-100M)_roll_6M
fcp_budget__Medium (20M-100M)_roll_9M
fcp_budget__Medium (20M-100M)_roll_1Y
fcp_budget__Large (>100M)_roll_3M
fcp_budget__Large (>100M)_roll_6M
fcp_budget__Large (>100M)_roll_9M
fcp_budget__Large (>100M)_roll_1Y
nightlight_annual_mean
nightlight_annual_max
nightlight_annual_std
nightlight_mean_pc1
nightlight_max_pc1
nightlight_std_pc1
nightlight_mean_pc2
nightlight_max_pc2
nightlight_std_pc2
reported_active_flood_days